# Use a base Python image
FROM python:3.10.12

# Set the working directory
WORKDIR /app

# Copy the requirements.txt file and install dependencies
COPY requirements.txt .    

RUN pip install --no-cache-dir -r requirements.txt
# Copy the application code into the container

COPY . .

# Expose the Flask app port
EXPOSE 5000

RUN chmod +x ./scripts/start_app.sh

CMD ["./scripts/start_app.sh"]