# Use a base Python image
FROM python:3.10.12

# Set the working directory
WORKDIR /app

# Copy the requirements.txt file and install dependencies
COPY requirements.txt .    

RUN pip install --no-cache-dir -r requirements.txt
# Copy the application code into the container
COPY . .

CMD celery -A worker worker --concurrency=1 --loglevel=info